name: Docker Image CI

on:
  push:
    branches:
      - "dollardollar-modular"
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push dev image
      if: github.ref == 'refs/heads/dollardollar-modular'
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: harung43/dollardollar:dev

    - name: Build and push demo image
      if: github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: harung43/dollardollar:demo