name: Docker Image CI
on:
  push:
    branches:
      - "main"
permissions:
  contents: read
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
       
    - name: Build and push main images
      if: github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ghcr.io/myanello/dollardollar:latest